import { AIAgent, RLHFFeedback, RLHFStats } from '../types';

export const aiAgents: AIAgent[] = [
  {
    id: 'agent-decision',
    name: 'Decision Analysis Agent',
    description: 'Analyzes incoming decisions, assesses risk, matches precedents, and generates recommendations',
    type: 'decision',
    status: 'active',
    model: 'GPT-4o (Fine-tuned)',
    version: '2.3.1',
    accuracy: 94.2,
    totalDecisions: 3847,
    avgResponseTime: 2340,
    lastUpdated: '2026-01-18T14:30:00Z',
    config: {
      temperature: 0.3,
      maxTokens: 4096,
      confidenceThreshold: 0.75,
      knowledgeSources: ['oracle_fusion', 'ecas', 'sharepoint', 'knowledge_graph'],
      promptTemplate: 'You are an AI decision analyst for the UAE Department of Government Enablement...',
    },
  },
  {
    id: 'agent-briefing',
    name: 'Executive Briefing Agent',
    description: 'Generates personalized briefings for the Chairman based on schedule, decisions, and organizational context',
    type: 'briefing',
    status: 'active',
    model: 'Claude 3.5 Sonnet',
    version: '1.8.0',
    accuracy: 96.8,
    totalDecisions: 1245,
    avgResponseTime: 1850,
    lastUpdated: '2026-01-17T09:15:00Z',
    config: {
      temperature: 0.5,
      maxTokens: 8192,
      confidenceThreshold: 0.8,
      knowledgeSources: ['calendar', 'email', 'knowledge_graph', 'decisions'],
      promptTemplate: 'Generate a concise executive briefing for the Chairman...',
    },
  },
  {
    id: 'agent-context',
    name: 'Context Assembly Agent',
    description: 'Retrieves and synthesizes relevant context from knowledge graph and connected data sources',
    type: 'context',
    status: 'active',
    model: 'GPT-4o-mini',
    version: '3.1.0',
    accuracy: 91.5,
    totalDecisions: 12540,
    avgResponseTime: 890,
    lastUpdated: '2026-01-19T06:00:00Z',
    config: {
      temperature: 0.1,
      maxTokens: 2048,
      confidenceThreshold: 0.7,
      knowledgeSources: ['knowledge_graph', 'oracle_fusion', 'ecas', 'sharepoint', 'tamm'],
    },
  },
  {
    id: 'agent-routing',
    name: 'Authority Routing Agent',
    description: 'Classifies decisions and routes them to appropriate authority level based on rules and context',
    type: 'routing',
    status: 'active',
    model: 'Rule-based + GPT-4o-mini',
    version: '2.0.5',
    accuracy: 98.1,
    totalDecisions: 8923,
    avgResponseTime: 450,
    lastUpdated: '2026-01-16T11:20:00Z',
    config: {
      temperature: 0.1,
      maxTokens: 1024,
      confidenceThreshold: 0.9,
      knowledgeSources: ['authority_matrix', 'policy_engine'],
    },
  },
  {
    id: 'agent-persona',
    name: 'Digital Persona Agent',
    description: 'Maintains and applies Chairman\'s communication preferences and decision patterns',
    type: 'persona',
    status: 'active',
    model: 'Claude 3.5 Sonnet (Fine-tuned)',
    version: '1.2.0',
    accuracy: 89.3,
    totalDecisions: 2156,
    avgResponseTime: 1200,
    lastUpdated: '2026-01-15T16:45:00Z',
    config: {
      temperature: 0.6,
      maxTokens: 4096,
      confidenceThreshold: 0.7,
      knowledgeSources: ['persona_settings', 'decision_history', 'communication_logs'],
    },
  },
  {
    id: 'agent-analysis',
    name: 'Risk Analysis Agent',
    description: 'Performs comprehensive risk assessment across financial, operational, and reputational dimensions',
    type: 'analysis',
    status: 'training',
    model: 'GPT-4o (Fine-tuning)',
    version: '2.4.0-beta',
    accuracy: 87.6,
    totalDecisions: 2890,
    avgResponseTime: 3200,
    lastUpdated: '2026-01-19T08:00:00Z',
    config: {
      temperature: 0.2,
      maxTokens: 6144,
      confidenceThreshold: 0.8,
      knowledgeSources: ['financial_data', 'market_data', 'stakeholder_graph', 'historical_outcomes'],
    },
  },
];

export const rlhfFeedback: RLHFFeedback[] = [
  {
    id: 'fb-001',
    decisionId: 'dec-001',
    agentId: 'agent-decision',
    rating: 'good',
    feedback: 'Recommendation aligned with strategic priorities. Risk assessment was accurate.',
    originalRecommendation: 'approve',
    submittedBy: 'Dr. Sarah Al Rashid',
    timestamp: '2026-01-18T10:30:00Z',
    incorporated: true,
  },
  {
    id: 'fb-002',
    decisionId: 'dec-005',
    agentId: 'agent-decision',
    rating: 'needs_improvement',
    feedback: 'Missed key stakeholder considerations. ADDA impact should have been flagged earlier.',
    originalRecommendation: 'approve',
    correctedRecommendation: 'defer',
    submittedBy: 'H.E. Mohammed Al Gergawi',
    timestamp: '2026-01-17T14:15:00Z',
    incorporated: true,
  },
  {
    id: 'fb-003',
    decisionId: 'dec-008',
    agentId: 'agent-routing',
    rating: 'excellent',
    feedback: 'Correctly escalated to Level 3 based on cross-entity implications.',
    originalRecommendation: 'escalate',
    submittedBy: 'Dr. Sarah Al Rashid',
    timestamp: '2026-01-16T09:45:00Z',
    incorporated: true,
  },
  {
    id: 'fb-004',
    decisionId: 'dec-012',
    agentId: 'agent-briefing',
    rating: 'good',
    feedback: 'Morning briefing was comprehensive. Appreciated the stakeholder context inclusion.',
    originalRecommendation: 'N/A',
    submittedBy: 'H.E. Mohammed Al Gergawi',
    timestamp: '2026-01-15T08:00:00Z',
    incorporated: true,
  },
  {
    id: 'fb-005',
    decisionId: 'dec-015',
    agentId: 'agent-decision',
    rating: 'incorrect',
    feedback: 'Failed to recognize time-sensitive nature. This required urgent escalation.',
    originalRecommendation: 'review',
    correctedRecommendation: 'escalate',
    submittedBy: 'Ahmed Al Mansoori',
    timestamp: '2026-01-14T16:30:00Z',
    incorporated: false,
  },
  {
    id: 'fb-006',
    decisionId: 'dec-018',
    agentId: 'agent-context',
    rating: 'needs_improvement',
    feedback: 'Context retrieval missed recent policy update. Need to improve sync frequency.',
    originalRecommendation: 'N/A',
    submittedBy: 'Fatima Al Zaabi',
    timestamp: '2026-01-13T11:20:00Z',
    incorporated: true,
  },
  {
    id: 'fb-007',
    decisionId: 'dec-020',
    agentId: 'agent-decision',
    rating: 'excellent',
    feedback: 'Outstanding precedent matching. Historical context was exactly what was needed.',
    originalRecommendation: 'approve',
    submittedBy: 'Omar Hassan',
    timestamp: '2026-01-12T15:00:00Z',
    incorporated: true,
  },
  {
    id: 'fb-008',
    decisionId: 'dec-022',
    agentId: 'agent-analysis',
    rating: 'good',
    feedback: 'Risk assessment was thorough. Financial projections aligned with finance review.',
    originalRecommendation: 'approve',
    submittedBy: 'Omar Hassan',
    timestamp: '2026-01-11T14:30:00Z',
    incorporated: true,
  },
];

export const rlhfStats: RLHFStats = {
  totalFeedback: 847,
  incorporated: 823,
  pending: 24,
  averageRating: 4.2,
  improvementTrend: 8.5,
};

// Helper functions
export const getAgentById = (id: string): AIAgent | undefined => 
  aiAgents.find(a => a.id === id);

export const getAgentsByStatus = (status: AIAgent['status']): AIAgent[] => 
  aiAgents.filter(a => a.status === status);

export const getFeedbackByAgent = (agentId: string): RLHFFeedback[] => 
  rlhfFeedback.filter(f => f.agentId === agentId);

export const getPendingFeedback = (): RLHFFeedback[] => 
  rlhfFeedback.filter(f => !f.incorporated);
