import { Stakeholder, Department } from '../types';

export const departments: Department[] = [
  {
    id: 'dept-1',
    name: 'Department of Government Enablement',
    shortName: 'DGE',
    headId: 'user-chairman',
    budget: 450000000,
    employeeCount: 280,
  },
  {
    id: 'dept-2',
    name: 'Strategy & Policy Coordination Office',
    shortName: 'SPCO',
    headId: 'stake-2',
    parentId: 'dept-1',
    budget: 85000000,
    employeeCount: 45,
  },
  {
    id: 'dept-3',
    name: 'Government Services Modernization',
    shortName: 'GSM',
    headId: 'stake-3',
    parentId: 'dept-1',
    budget: 120000000,
    employeeCount: 95,
  },
  {
    id: 'dept-4',
    name: 'Corporate Services',
    shortName: 'CS',
    headId: 'stake-4',
    parentId: 'dept-1',
    budget: 35000000,
    employeeCount: 40,
  },
  {
    id: 'dept-5',
    name: 'Finance & Procurement',
    shortName: 'F&P',
    headId: 'stake-5',
    parentId: 'dept-1',
    budget: 25000000,
    employeeCount: 35,
  },
  {
    id: 'dept-6',
    name: 'Department of Finance',
    shortName: 'DoF',
    headId: 'stake-6',
    budget: 2500000000,
    employeeCount: 850,
  },
  {
    id: 'dept-7',
    name: 'Abu Dhabi Digital Authority',
    shortName: 'ADDA',
    headId: 'stake-7',
    budget: 320000000,
    employeeCount: 450,
  },
  {
    id: 'dept-8',
    name: 'Executive Council Secretariat',
    shortName: 'ECS',
    headId: 'stake-8',
    budget: 180000000,
    employeeCount: 120,
  },
];

export const stakeholders: Stakeholder[] = [
  {
    id: 'stake-1',
    name: 'H.E. Sultan bin Ahmed Al Jaber',
    title: 'Undersecretary',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 's.aljaber@dge.abudhabi.ae',
    phone: '+971 2 333 4000',
    relationshipScore: 95,
    lastInteraction: '2026-01-19T08:30:00Z',
    openItems: 3,
    pendingDecisions: 7,
    totalMeetings: 245,
    totalEmails: 1820,
    positions: [
      { topic: 'Government Services Enhancement Program', stance: 'supportive', notes: 'Priority initiative for 2026' },
      { topic: 'Cross-Entity Coordination', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-2',
    name: 'Fatima Al Suwaidi',
    title: 'Director, Strategy & Policy Coordination',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 'f.alsuwaidi@dge.abudhabi.ae',
    relationshipScore: 88,
    lastInteraction: '2026-01-18T14:00:00Z',
    openItems: 2,
    pendingDecisions: 4,
    totalMeetings: 156,
    totalEmails: 890,
    positions: [
      { topic: 'Abu Dhabi Government Excellence Framework', stance: 'supportive' },
      { topic: 'Strategic KPIs 2026', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-3',
    name: 'Mohammed Al Zaabi',
    title: 'Director, Government Services Modernization',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 'm.alzaabi@dge.abudhabi.ae',
    relationshipScore: 82,
    lastInteraction: '2026-01-17T10:00:00Z',
    openItems: 5,
    pendingDecisions: 3,
    totalMeetings: 89,
    totalEmails: 456,
    positions: [
      { topic: 'TAMM Platform Enhancement', stance: 'supportive', notes: 'Leading digital services integration' },
      { topic: 'Unified Services Framework', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-4',
    name: 'Aisha Al Shamsi',
    title: 'Director, Corporate Services',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 'a.alshamsi@dge.abudhabi.ae',
    relationshipScore: 91,
    lastInteraction: '2026-01-19T09:00:00Z',
    openItems: 1,
    pendingDecisions: 2,
    totalMeetings: 178,
    totalEmails: 1240,
    positions: [
      { topic: 'Workforce Development Strategy', stance: 'supportive' },
      { topic: 'Emiratization Targets', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-5',
    name: 'Khalid Al Marzooqi',
    title: 'Director, Finance & Procurement',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 'k.almarzooqi@dge.abudhabi.ae',
    relationshipScore: 85,
    lastInteraction: '2026-01-18T16:00:00Z',
    openItems: 4,
    pendingDecisions: 5,
    totalMeetings: 134,
    totalEmails: 780,
    positions: [
      { topic: 'Q1 Budget Execution', stance: 'neutral', notes: 'Monitoring spend rate' },
      { topic: 'Procurement Framework Update', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-6',
    name: 'H.E. Riyad Al Mubarak',
    title: 'Undersecretary',
    organization: 'Department of Finance',
    type: 'government',
    email: 'r.almubarak@dof.abudhabi.ae',
    relationshipScore: 78,
    lastInteraction: '2026-01-15T11:00:00Z',
    openItems: 2,
    pendingDecisions: 1,
    totalMeetings: 23,
    totalEmails: 145,
    positions: [
      { topic: 'Cross-Government Budget Coordination', stance: 'supportive' },
      { topic: 'Shared Services Cost Model', stance: 'neutral' },
    ],
  },
  {
    id: 'stake-7',
    name: 'H.E. Ali Al Ketbi',
    title: 'Director General',
    organization: 'Abu Dhabi Digital Authority',
    type: 'government',
    email: 'a.alketbi@adda.abudhabi.ae',
    relationshipScore: 85,
    lastInteraction: '2026-01-16T14:30:00Z',
    openItems: 3,
    pendingDecisions: 2,
    totalMeetings: 42,
    totalEmails: 234,
    positions: [
      { topic: 'TAMM Platform Integration', stance: 'supportive', notes: 'Key partner for digital services' },
      { topic: 'Government Cloud Infrastructure', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-8',
    name: 'Salem Al Dhaheri',
    title: 'Director of Government Coordination',
    organization: 'Executive Council Secretariat',
    type: 'government',
    email: 's.aldhaheri@ecs.abudhabi.ae',
    relationshipScore: 81,
    lastInteraction: '2026-01-14T10:00:00Z',
    openItems: 1,
    pendingDecisions: 1,
    totalMeetings: 34,
    totalEmails: 178,
    positions: [
      { topic: 'Executive Council Reporting', stance: 'supportive' },
      { topic: 'Policy Coordination Framework', stance: 'supportive' },
    ],
  },
  {
    id: 'stake-9',
    name: 'Ahmad Hassan',
    title: 'Managing Director, UAE',
    organization: 'Dynamiq Technologies',
    type: 'external',
    email: 'ahmad.hassan@dynamiq.ai',
    relationshipScore: 75,
    lastInteraction: '2026-01-17T09:00:00Z',
    openItems: 2,
    pendingDecisions: 1,
    totalMeetings: 18,
    totalEmails: 89,
    positions: [
      { topic: 'Agent-0 Implementation', stance: 'supportive', notes: 'Implementation partner' },
      { topic: 'AI Platform Licensing', stance: 'neutral' },
    ],
  },
  {
    id: 'stake-10',
    name: 'Sara Al Nuaimi',
    title: 'Head of Innovation & AI',
    organization: 'Department of Government Enablement',
    type: 'internal',
    email: 's.alnuaimi@dge.abudhabi.ae',
    relationshipScore: 93,
    lastInteraction: '2026-01-19T10:00:00Z',
    openItems: 6,
    pendingDecisions: 4,
    totalMeetings: 167,
    totalEmails: 1450,
    positions: [
      { topic: 'AI-Powered Decision Support', stance: 'supportive', notes: 'Project lead for Agent-0' },
      { topic: 'Responsible AI Framework', stance: 'supportive' },
      { topic: 'Data Governance Standards', stance: 'supportive' },
    ],
  },
];

export const getStakeholderById = (id: string): Stakeholder | undefined => {
  return stakeholders.find(s => s.id === id);
};

export const getDepartmentById = (id: string): Department | undefined => {
  return departments.find(d => d.id === id);
};

export const getStakeholdersByType = (type: Stakeholder['type']): Stakeholder[] => {
  return stakeholders.filter(s => s.type === type);
};

export const getStakeholdersByDepartment = (departmentId: string): Stakeholder[] => {
  const dept = getDepartmentById(departmentId);
  if (!dept) return [];
  return stakeholders.filter(s => s.organization === dept.name);
};
